---
resource_types:
  - name:  pull-request
    type: docker-image
    source:
      repository: jtarchie/pr
resources:
  - name: super-app
    type: pull-request
    source:
      repo: pnhoang/concourse-tutorial
      access_token: {{github_token}}

jobs:
  - name: PR unit testing
    plan:
    - get: super-app
      trigger: true

    - put: super-app
      params: {path: super-app, context: Unit Tests, status: pending}

    - task: run unit
      file: super-app/class/tasks/unit.yml
      on_success:
        put: super-app
        params: {path: super-app, context: Unit Tests, status: success}
      on_failure:
        put: super-app
        params: {path: super-app, context: Unit Tests, status: failure}




